# Generated by Django 4.0.3 on 2022-03-29 11:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import tables.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField(help_text="Latitude of the table's geographic location")),
                ('location_lon', models.FloatField(help_text="Longitude of the table's geographic location")),
                ('ports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(tables.models.PortType['USB'], 'USB'), (tables.models.PortType['QI'], 'Qi')], max_length=5), help_text='Port types', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of this snapshot')),
                ('energy_production', models.FloatField(help_text='Current energy production by the PV panel')),
                ('battery_charge', models.FloatField(help_text='Current battery charge')),
                ('port_usage', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='Port usage'), help_text='For mapping to port types, refer to the ports field of the corresponding table', size=None)),
                ('table', models.ForeignKey(help_text='Table which this snapshot refers to', on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
        ),
    ]
