# Generated by Django 4.0.3 on 2022-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
