# Generated by Django 4.0.3 on 2022-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(help_text='Displayable name', max_length=50),
        ),
    ]
