# Generated by Django 4.0.3 on 2022-10-20 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesnapshot',
            name='port_voltage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='Voltage at the USB ports'), default=[3.0], help_text='For mapping to port types, refer to the ports field of the corresponding table', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='battery_charge',
            field=models.FloatField(help_text='Current battery charge (expressed as battery voltage)'),
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='energy_production',
            field=models.FloatField(help_text='Current energy production by the PV panel in mA'),
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='port_usage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='Power draw at the USB ports in mA'), help_text='For mapping to port types, refer to the ports field of the corresponding table', size=None),
        ),
        migrations.AlterField(
            model_name='tablesnapshot',
            name='timestamp',
            field=models.DateTimeField(help_text='Timestamp of this snapshot'),
        ),
    ]
