# Generated by Django 4.0.3 on 2022-12-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tablesnapshot_port_voltage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesnapshot',
            name='temperature',
            field=models.FloatField(help_text='Temperature in °C', null=True),
        ),
    ]
