# Generated by Django 4.0.3 on 2022-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of this snapshot')),
                ('text', models.TextField(help_text='User-provided description')),
                ('user_email', models.TextField(help_text='Optional e-mail address of the user for responding', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this report has been resolved')),
            ],
        ),
    ]
